---
- hosts: all
  become: true

  tasks:
    - import_tasks: tasks/essential.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/jellyfin.yml
    - import_tasks: tasks/gitea.yml
    - import_tasks: tasks/adguardhome.yml
