---
- name: Setup AdGuardHome container
  docker_container:
    name: AdGuardHome
    image: adguard/adguardhome
    pull: true
    published_ports:
      # Plain DNS
      # https://github.com/sameersbn/docker-bind/issues/65
      - "127.0.0.1:53:53/tcp"
      - "127.0.0.1:53:53/udp"
      # Admin panel + HTTPS/DNS-over-HTTPS
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "3000:3000/tcp"
    volumes:
      - /work:/opt/adguardhome/work
      - /conf:/opt/adguardhome/conf
    restart_policy: unless-stopped
