---
- name: Install required system packages
  package:
    state: latest
    name: "{{ docker_deps }}"

- name: Install Docker
  block:
  - name: Add Docker GPG apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add Docker repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present
  - name: Switch to pip3
    alternatives:
      name: pip
      link: /usr/bin/pip
      path: /usr/bin/pip3
  - name: Switch to python3
    alternatives:
      name: python
      link: /usr/bin/python
      path: /usr/bin/python3

- name: Setup Docker basics
  block:
  - name: Update apt and install Docker packages
    apt:
      update_cache: true
      name: "{{ docker_packages }}"
      state: latest
  - name: Ensure group docker exists
    group:
      name: docker
      state: present
  - name: Add user "{{ username }}" to group docker
    user:
      name: "{{ username }}"
      groups:
      - docker
      append: true
  - name: Install Docker module for Python
    pip:
      name: docker
  - name: Make sure Docker is running and enabled
    service:
      name: docker
      state: started
      enabled: true
