---
- name: Install required system packages
  package:
    state: latest
    name: "{{ docker_deps }}"

- name: Install Docker
  block:
  - name: Add Docker GPG apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add Docker repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

- name: Setup Docker basics
  block:
  - name: Update apt and install Docker packages
    apt:
      update_cache: yes
      name: "{{ docker_packages }}"
      state: latest
  - name: Ensure group docker exists
    group:
      name: docker
      state: present
  - name: Add user "{{ username }}" to group docker
    user:
      name: "{{ username }}"
      groups:
      - docker
      append: yes
  - name: Install Docker module for Python
    pip:
      name: docker
  - name: Make sure Docker is running and enabled
    service:
      name: docker
      state: started
      enabled: yes
