---
username: arya
packages:
  - vim
  - htop
  - neofetch
  - git
  - net-tools

enable_electron_cloud: true

# Docker
timezone: Pacific/Auckland
guid: "1000"

docker_deps:
  - 'apt-transport-https'
  - 'ca-certificates'
  - 'curl'
  - 'software-properties-common'
  - 'python3-pip'
  - 'virtualenv'
  - 'python3-setuptools'
  - 'docker-compose'
docker_packages:
  - 'docker-ce'
  - 'docker-compose'

# Gitea
gitea_user: gitea
gitea_group: gitea
gitea_home: "/var/lib/gitea"
gitea_repository_root: "{{ gitea_home }}"
gitea_network: giteaNET
gitea_dependencies:
  - git
  - gnupg2
  - xz-utils
